#!/bin/bash 

# This script is used to self initialize the preinstalled acitoolkit VM

apt-get -y update
apt-get -y upgrade
apt-get install python-dev
cd acitoolkit
git pull
python setup.py develop
/etc/init.d/mysql start
